function [ Result ] = getpricing ()
C = main_par() ;

Result = cellfun(    @(n,m,sex,gp_scenario,buy_age_max,buy_age_min,i,i_v,bp_max,SA,tso_filing,tso_valuation)   ...
                 t_xxx(n,m,sex,gp_scenario,buy_age_max,buy_age_min,i,i_v,bp_max,SA,tso_filing,tso_valuation)   ...
                     ,C.n                                                      ... 
				     ,C.m                                                      ...
				     ,C.sex                                                    ... 
				     ,C.gp_scenario                                            ...
				     ,C.buy_age_max                                            ...
				     ,C.buy_age_min                                            ...
				     ,C.i                                                      ...
					 ,C.i_v                                                    ...
				     ,C.bp_max                                                 ...
					 ,C.SA                                                     ...
					 ,C.tso_filing                                             ...
					 ,C.tso_valuation                                          ...
				     ,'UniformOutput',false                                    ...
				);


%get element of cell must use  { } not ( _) 
%Example
% octave:27> a=Result{1};
% octave:28> a.Benefit;
% octave:29> a.Benefit.PV;

end
